### ISSUE TITLE
All Notifier subscriptions made in select.rs appear to be leaked

### ISSUE THREAD

**Issue by gwillen** [BurntSushi/chan#6]
Hello! I have been debugging a gradual misbehavior of some code that's using the chan module. 

I seem to have tracked this issue down to the following bug in select.rs (line numbers reference https://github.com/BurntSushi/chan/blob/955d8a5aecef77c1a380bd2c8265b9efed83103b/src/select.rs ):

in Choice::subscribe on line 281 (and 329), we discard the return value from Notifier::subscribe.

in Choice::unsubscribe on line 285 (and 333), we match against self.id to find the id of our subscription; but we have never saved the id of our subscription, and self.id is always None.

I haven't verified the dynamic behavior that self.id is always None, but I have verified using a breakpoint that Notifier::unsubscribe seems never to be called. I also find that after more than a week of operation, our subscription hashtable has 445k entries:

(gdb) p (*notify.__data).value.subscriptions.table.size
$10 = 445594

and we were spending a lot of CPU cycles iterating over the subscription list, which is what lead me to take a closer look at subscriptions in the first place.

Let me know if you'd like any further info.

Thanks!

**Comment by BurntSushi** [comment]
I think I agree with your analysis, very nice! I'm working on a regression test now, and then hopefully a fix will be easy.

**Comment by gwillen** [comment]
Awesome, thanks a lot for looking into this. :-) I will note my concern that -- in light of this bug -- there is some code on this path (e.g. the notifier unsubscribe method) which has clearly never been actually exercised, so even after the fix I am concerned about what other bugs may lurk. (I'm not asking you to _do_ anything about that unless it seems like a good use of your time, just pointing it out.) Thanks again!

**Comment by BurntSushi** [comment]
@gwillen You should be all set now. The fix is in `0.1.16` on crates.io.

> Awesome, thanks a lot for looking into this. :-) I will note my concern that -- in light of this bug -- there is some code on this path (e.g. the notifier unsubscribe method) which has clearly never been actually exercised, so even after the fix I am concerned about what other bugs may lurk. (I'm not asking you to do anything about that unless it seems like a good use of your time, just pointing it out.) Thanks again!

The version number of this library unfortunately reflects its maturity. I think it just doesn't have that many users yet, so there hasn't been much experience actually using this library. I have some applications in mind myself that should stress the implementation more, but it might take me a few months (or more) to get there.

I think at this point, the most valuable thing you could provide is experience using the library. Similarly, input on other issues like this one: https://github.com/BurntSushi/chan/issues/2 would be quite valuable.
